import React from "react";  
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LoadingSpinner from "./components/loadingSpinner";
import Header from "./components/header";
import Footer from "./components/footer";
import { GenerationProvider } from "./contexts/generationContext"; // Import GenerationProvider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <GenerationProvider> {/* Wrap with GenerationProvider */}
          <Header/>
          {/* Suspense boundary for server-side rendering */}
          <React.Suspense fallback={<LoadingSpinner />}>
            {children}
          </React.Suspense>
          <Footer/>
        </GenerationProvider>
      </body>
    </html>
  );
}
